import { StatusBar } from 'expo-status-bar';
import { SafeAreaView, StyleSheet, ScrollView, Text, View } from 'react-native';

//Provides information about the privacy policy
function PrivacyPolicy() {
    return (
      <SafeAreaView style={styles.container}>
        <ScrollView>
          {/* Header */}
          <View style={styles.header}> 
            <Text style={{fontSize: 30, textAlign: 'center'}}>Privacy Policy</Text>
          </View> 
    
          {/* Introduction */}
          <View style={styles.textView}>
            <Text style={{fontStyle: 'italic', marginBottom:15}}>Last updated: March 03, 2022 </Text>
            <Text style={styles.basicText}>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. </Text>
            <Text style={styles.basicText}>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Template. </Text>
          </View>

          {/* Interpretation and Definitions */}
          <View style={styles.textView}>
            <Text style={styles.heading}>Interpretation and Definitions</Text>
            {/* Interpretation */}
            <Text style={styles.subheading}>Interpretation</Text>
            <Text style={styles.basicText}>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural. </Text>
            {/* Definitions */}
            <Text style={styles.subheading}>Definitions</Text>
            <Text style={styles.basicText}>For the purposes of this Privacy Policy: </Text>
            <Text style={styles.listItem}>■ Account means a unique account created for You to access our Service or parts of our Service. </Text>
            <Text style={styles.listItem}>■ Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority. </Text>
            <Text style={styles.listItem}>■ Application means the software program provided by the Company downloaded by You on any electronic device, named Heart App </Text>
            <Text style={styles.listItem}>■ Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Asghar Lab - Micro and Nanotechnology in Medicine, 777 Glades Road, EE 96/Rm 435, Boca Raton, FL 33431. </Text>
            <Text style={styles.listItem}>■ Country refers to: Florida, United States </Text>
            <Text style={styles.listItem}>■ Device means any device that can access the Service such as a computer, a cellphone or a digital tablet. </Text>
            <Text style={styles.listItem}>■ Personal Data is any information that relates to an identified or identifiable individual. </Text>
            <Text style={styles.listItem}>■ Service refers to the Application. </Text>
            <Text style={styles.listItem}>■ Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. </Text>
            <Text style={styles.listItem}>■ Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). </Text>
            <Text style={styles.listItem}>■ You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable. </Text>
          </View>

          {/* Collecting and Using Your Personal Data  */}
          <View style={styles.textView}>
            <Text style={styles.heading}>Collecting and Using Your Personal Data </Text>
            {/* Types of Data Collected */}
            <Text style={styles.subheading}>Types of Data Collected</Text>
            {/* Personal Data */}
            <Text style={styles.subSubheading}>Personal Data</Text>
            <Text style={styles.basicText}>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: </Text>
            <Text style={styles.listItem}>■ Email address</Text>
            <Text style={styles.listItem}>■ First name and last name </Text>
            <Text style={styles.listItem}>■ Usage Data </Text>
            {/* Usage Data */}
            <Text style={styles.subSubheading}>Usage Data</Text>
            <Text style={styles.basicText}>Usage Data is collected automatically when using the Service. </Text>
            <Text style={styles.basicText}>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. </Text>
            <Text style={styles.basicText}>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data. </Text>
            <Text style={styles.basicText}>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device. </Text>

            {/* Use of Your Personal Data  */}
            <Text style={styles.subheading}>Use of Your Personal Data </Text>
            <Text style={styles.basicText}>The Company may use Personal Data for the following purposes: </Text>
            <Text style={styles.listItem}>■ To provide and maintain our Service, including to monitor the usage of our Service. </Text>
            <Text style={styles.listItem}>■ To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user. </Text>
            <Text style={styles.listItem}>■ For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service. </Text>
            <Text style={styles.listItem}>■ To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation. </Text>
            <Text style={styles.listItem}>■ To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information. </Text>
            <Text style={styles.listItem}>■ To manage Your requests: To attend and manage Your requests to Us. </Text>
            <Text style={styles.listItem}>■ For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred. </Text>
            <Text style={styles.listItem}>■ For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience. </Text>
            
            <Text style={styles.basicText}>We may share Your personal information in the following situations: </Text>
            <Text style={styles.listItem}>■ With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You. </Text>
            <Text style={styles.listItem}>■ For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company. </Text>
            <Text style={styles.listItem}>■ With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us. </Text>
            <Text style={styles.listItem}>■ With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions. </Text>
            <Text style={styles.listItem}>■ With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. </Text>
            <Text style={styles.listItem}>■ With Your consent: We may disclose Your personal information for any other purpose with Your consent. </Text>

            {/* Retention of Your Personal Data */}
            <Text style={styles.subheading}>Retention of Your Personal Data</Text>
            <Text style={styles.basicText}>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies. </Text>
            <Text style={styles.basicText}>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods. </Text>

            {/* Transfer of Your Personal Data */}
            <Text style={styles.subheading}>Transfer of Your Personal Data</Text>
            <Text style={styles.basicText}>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction. </Text>
            <Text style={styles.basicText}>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer. </Text>
            <Text style={styles.basicText}>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information. </Text>
           
            {/* Disclosure of Your Personal Data */}
            <Text style={styles.subheading}>Disclosure of Your Personal Data</Text>
            {/* Business Transactions */}
            <Text style={styles.subSubheading}>Business Transactions</Text>
            <Text style={styles.basicText}>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy. </Text>
            {/* Law enforcement */}
            <Text style={styles.subSubheading}>Law enforcement</Text>
            <Text style={styles.basicText}>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency). </Text>
            {/* Other legal requirements */}
            <Text style={styles.subSubheading}>Other legal requirements</Text>
            <Text style={styles.basicText}>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to: </Text>
            <Text style={styles.listItem}>■ Comply with a legal obligation </Text>
            <Text style={styles.listItem}>■ Protect and defend the rights or property of the Company </Text>
            <Text style={styles.listItem}>■ Prevent or investigate possible wrongdoing in connection with the Service </Text>
            <Text style={styles.listItem}>■ Protect the personal safety of Users of the Service or the public </Text>
            <Text style={styles.listItem}>■ Protect against legal liability </Text>
          </View>


          {/* Children's Privacy */}
          <View style={styles.textView}>
            <Text style={styles.heading}>Children's Privacy</Text>
            <Text style={styles.basicText}>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers. </Text>
            <Text style={styles.basicText}>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information. </Text>
          </View>

          {/* Links to Other Websites */}
          <View style={styles.textView}>
            <Text style={styles.heading}>Links to Other Websites</Text>
            <Text style={styles.basicText}>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. </Text>
            <Text style={styles.basicText}>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services. </Text>
          </View>

          {/* Changes to this Privacy Policy */}
          <View style={styles.textView}>
            <Text style={styles.heading}>Changes to this Privacy Policy</Text>
            <Text style={styles.basicText}>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. </Text>
            <Text style={styles.basicText}>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy. </Text>
            <Text style={styles.basicText}>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page. </Text>
          </View>

          {/* Contact Us */}
          <View style={styles.textView}>
            <Text style={styles.heading}>Contact Us</Text>
            <Text style={styles.basicText}>If you have any questions about this Privacy Policy, You can contact us: </Text>
            <Text style={styles.listItem}>■ By email: hearthealthfau@gmail.com </Text>
          </View>

          <StatusBar style="auto" />
        </ScrollView>
      </SafeAreaView>
    );
  }

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    alignItems: 'center',
    alignContent: 'center',
  },
  header: {
    paddingTop: 30,
    margin: 30
  },
  basicText: {
    marginBottom:15
  },
  heading: {
    fontSize: 25,
    color: '#1c406b',
    marginTop: 30,
    marginBottom: 15,
  },
  subheading: {
    fontWeight: 'bold',
    color: '#4f81bd',
    fontSize: 18,
    marginBottom:15,
    marginTop: 15
  },
  listItem: {
    marginLeft: 20,
    marginBottom: 5
  },
  textView: {
    marginLeft: 30, 
    marginRight: 30
  },
  subSubheading: {
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 10,
    marginTop: 10
  }
});

export default PrivacyPolicy;